-- Task: TASK_PATIENT_COUNT
-- Purpose: Runs SP_PATIENT_COUNT_SCHEDULED every 5 minutes, auto-suspends after 2 runs
-- Database: LEARNING_DB | Schema: HEALTH_DATA

-- Run log table (tracks execution count)
CREATE OR REPLACE TABLE LEARNING_DB.HEALTH_DATA.TASK_RUN_LOG (
    RUN_ID INT AUTOINCREMENT,
    TASK_NAME VARCHAR(100),
    RUN_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR(50)
);

-- Task definition
CREATE OR REPLACE TASK LEARNING_DB.HEALTH_DATA.TASK_PATIENT_COUNT
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
AS
    CALL LEARNING_DB.HEALTH_DATA.SP_PATIENT_COUNT_SCHEDULED();

-- Activate the task
ALTER TASK LEARNING_DB.HEALTH_DATA.TASK_PATIENT_COUNT RESUME;
