-- Test: Validate V001 - PATIENT_EVENTS table exists and has correct structure
-- Expected: table exists, has correct columns, FK constraints, and test data

-- Test 1: Table exists
SELECT COUNT(*) AS TABLE_EXISTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HEALTH_DATA' AND TABLE_NAME = 'PATIENT_EVENTS';
-- ASSERT: TABLE_EXISTS = 1

-- Test 2: Has required columns
SELECT COUNT(*) AS COL_COUNT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HEALTH_DATA'
  AND TABLE_NAME = 'PATIENT_EVENTS'
  AND COLUMN_NAME IN ('EVENT_ID','PATIENT_ID','FACILITY_ID','EVENT_TYPE','SEVERITY','EVENT_TIMESTAMP');
-- ASSERT: COL_COUNT = 6

-- Test 3: No orphan PATIENT_IDs (FK integrity)
SELECT COUNT(*) AS ORPHAN_PATIENTS
FROM HEALTH_DATA.PATIENT_EVENTS e
LEFT JOIN HEALTH_DATA.PATIENTS p ON e.PATIENT_ID = p.PATIENT_ID
WHERE p.PATIENT_ID IS NULL;
-- ASSERT: ORPHAN_PATIENTS = 0

-- Test 4: No orphan FACILITY_IDs (FK integrity)
SELECT COUNT(*) AS ORPHAN_FACILITIES
FROM HEALTH_DATA.PATIENT_EVENTS e
LEFT JOIN HEALTH_DATA.FACILITIES f ON e.FACILITY_ID = f.FACILITY_ID
WHERE f.FACILITY_ID IS NULL;
-- ASSERT: ORPHAN_FACILITIES = 0

-- Test 5: Row count > 0
SELECT COUNT(*) AS ROW_COUNT FROM HEALTH_DATA.PATIENT_EVENTS;
-- ASSERT: ROW_COUNT >= 10
