-- Test: Validate V002 - New columns added to PATIENT_EVENTS
-- Expected: IS_RESOLVED, RESOLVED_BY, RESOLVED_AT columns exist

SELECT COUNT(*) AS NEW_COLS
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HEALTH_DATA'
  AND TABLE_NAME = 'PATIENT_EVENTS'
  AND COLUMN_NAME IN ('IS_RESOLVED', 'RESOLVED_BY', 'RESOLVED_AT');
-- ASSERT: NEW_COLS = 3
