-- Test: Validate V003 - CDC stream and task exist
-- Expected: Stream and task are created and active

-- Test 1: Stream exists
SELECT COUNT(*) AS STREAM_EXISTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HEALTH_DATA' AND TABLE_NAME = 'STREAM_PATIENT_EVENTS' AND TABLE_TYPE = 'BASE TABLE';
-- Note: streams don't show in INFORMATION_SCHEMA.TABLES, use SHOW instead

-- Test 2: Summary table exists
SELECT COUNT(*) AS SUMMARY_TABLE_EXISTS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HEALTH_DATA' AND TABLE_NAME = 'PATIENT_EVENTS_DAILY_SUMMARY';
-- ASSERT: SUMMARY_TABLE_EXISTS = 1

-- Test 3: Change tracking is enabled on source
SELECT COUNT(*) AS CHANGE_TRACKING_ON
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HEALTH_DATA'
  AND TABLE_NAME = 'PATIENT_EVENTS'
  AND CHANGE_TRACKING = 'YES';
-- ASSERT: CHANGE_TRACKING_ON = 1
