-- Migration V002: Add RESOLVED column to PATIENT_EVENTS
-- Business requirement: Need to track whether events have been reviewed/resolved

ALTER TABLE HEALTH_DATA.PATIENT_EVENTS ADD COLUMN IS_RESOLVED BOOLEAN DEFAULT FALSE;
ALTER TABLE HEALTH_DATA.PATIENT_EVENTS ADD COLUMN RESOLVED_BY VARCHAR(100);
ALTER TABLE HEALTH_DATA.PATIENT_EVENTS ADD COLUMN RESOLVED_AT TIMESTAMP_NTZ;
