-- Migration V003: Create CDC stream and daily processing task
-- Stream captures changes (INSERT/UPDATE/DELETE) on PATIENT_EVENTS
-- Task runs daily to process new events into a summary table

-- 1. Enable change tracking on source table
ALTER TABLE HEALTH_DATA.PATIENT_EVENTS SET CHANGE_TRACKING = TRUE;

-- 2. Create stream to capture changes
CREATE OR REPLACE STREAM HEALTH_DATA.STREAM_PATIENT_EVENTS
    ON TABLE HEALTH_DATA.PATIENT_EVENTS
    SHOW_INITIAL_ROWS = FALSE;

-- 3. Create daily summary table (CDC target)
CREATE TABLE IF NOT EXISTS HEALTH_DATA.PATIENT_EVENTS_DAILY_SUMMARY (
    SUMMARY_DATE DATE,
    FACILITY_ID INT,
    FACILITY_NAME VARCHAR(200),
    TOTAL_EVENTS INT,
    HIGH_SEVERITY_COUNT INT,
    FALL_COUNT INT,
    VITAL_ALERT_COUNT INT,
    PROCESSED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 4. Create task that processes stream data daily
CREATE OR REPLACE TASK HEALTH_DATA.TASK_PROCESS_EVENTS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1440 MINUTE'  -- daily (24 hours)
    WHEN SYSTEM$STREAM_HAS_DATA('HEALTH_DATA.STREAM_PATIENT_EVENTS')
AS
    INSERT INTO HEALTH_DATA.PATIENT_EVENTS_DAILY_SUMMARY
        (SUMMARY_DATE, FACILITY_ID, FACILITY_NAME, TOTAL_EVENTS, HIGH_SEVERITY_COUNT, FALL_COUNT, VITAL_ALERT_COUNT)
    SELECT
        CURRENT_DATE() AS SUMMARY_DATE,
        s.FACILITY_ID,
        f.FACILITY_NAME,
        COUNT(*) AS TOTAL_EVENTS,
        SUM(CASE WHEN s.SEVERITY = 'HIGH' THEN 1 ELSE 0 END) AS HIGH_SEVERITY_COUNT,
        SUM(CASE WHEN s.EVENT_TYPE = 'FALL' THEN 1 ELSE 0 END) AS FALL_COUNT,
        SUM(CASE WHEN s.EVENT_TYPE = 'VITAL_ALERT' THEN 1 ELSE 0 END) AS VITAL_ALERT_COUNT
    FROM HEALTH_DATA.STREAM_PATIENT_EVENTS s
    JOIN HEALTH_DATA.FACILITIES f ON s.FACILITY_ID = f.FACILITY_ID
    WHERE s.METADATA$ACTION = 'INSERT'
    GROUP BY s.FACILITY_ID, f.FACILITY_NAME;

-- 5. Resume task
ALTER TASK HEALTH_DATA.TASK_PROCESS_EVENTS RESUME;
