-- Monitoring Views for Credit Consumption
-- Database: LEARNING_DB | Schema: MONITORING

CREATE SCHEMA IF NOT EXISTS LEARNING_DB.MONITORING
    COMMENT = 'Credit monitoring views and alerts';

----------------------------------------------------------------------
-- VIEW 1: Daily credit usage by warehouse
----------------------------------------------------------------------
CREATE OR REPLACE VIEW LEARNING_DB.MONITORING.VW_CREDIT_USAGE_BY_WAREHOUSE AS
SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
    SUM(CREDITS_USED) AS CREDITS_USED,
    SUM(CREDITS_USED_COMPUTE) AS CREDITS_COMPUTE,
    SUM(CREDITS_USED_CLOUD_SERVICES) AS CREDITS_CLOUD_SERVICES,
    ROUND(SUM(CREDITS_USED), 2) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('DAY', START_TIME)
ORDER BY USAGE_DATE DESC, TOTAL_CREDITS DESC;

----------------------------------------------------------------------
-- VIEW 2: Budget status (% consumed vs remaining)
----------------------------------------------------------------------
CREATE OR REPLACE VIEW LEARNING_DB.MONITORING.VW_CREDIT_BUDGET_STATUS AS
SELECT
    400 AS TOTAL_BUDGET_CREDITS,
    ROUND(SUM(CREDITS_USED), 2) AS CREDITS_CONSUMED,
    ROUND(400 - SUM(CREDITS_USED), 2) AS CREDITS_REMAINING,
    ROUND((SUM(CREDITS_USED) / 400) * 100, 1) AS PERCENT_USED,
    ROUND(((400 - SUM(CREDITS_USED)) / 400) * 100, 1) AS PERCENT_REMAINING
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATE_TRUNC('MONTH', CURRENT_TIMESTAMP());

----------------------------------------------------------------------
-- VIEW 3: Credit usage by task (serverless)
----------------------------------------------------------------------
CREATE OR REPLACE VIEW LEARNING_DB.MONITORING.VW_CREDIT_USAGE_BY_TASK AS
SELECT
    DATABASE_NAME,
    SCHEMA_NAME,
    TASK_NAME,
    DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
    SUM(CREDITS_USED) AS CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.SERVERLESS_TASK_HISTORY
WHERE START_TIME >= DATEADD('DAY', -30, CURRENT_TIMESTAMP())
GROUP BY DATABASE_NAME, SCHEMA_NAME, TASK_NAME, DATE_TRUNC('DAY', START_TIME)
ORDER BY USAGE_DATE DESC, CREDITS_USED DESC;

----------------------------------------------------------------------
-- VIEW 4: Top credit consumers (warehouses + tasks combined)
----------------------------------------------------------------------
CREATE OR REPLACE VIEW LEARNING_DB.MONITORING.VW_TOP_CREDIT_CONSUMERS AS
SELECT
    'WAREHOUSE' AS CATEGORY,
    WAREHOUSE_NAME AS CONSUMER_NAME,
    ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS,
    ROUND((SUM(CREDITS_USED) / 400) * 100, 2) AS PERCENT_OF_BUDGET
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATE_TRUNC('MONTH', CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME

UNION ALL

SELECT
    'TASK' AS CATEGORY,
    TASK_NAME AS CONSUMER_NAME,
    ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS,
    ROUND((SUM(CREDITS_USED) / 400) * 100, 2) AS PERCENT_OF_BUDGET
FROM SNOWFLAKE.ACCOUNT_USAGE.SERVERLESS_TASK_HISTORY
WHERE START_TIME >= DATE_TRUNC('MONTH', CURRENT_TIMESTAMP())
GROUP BY TASK_NAME

ORDER BY TOTAL_CREDITS DESC;
