-- Stored Procedure: SP_PATIENT_COUNT_BY_FACILITY
-- Purpose: Counts total patients per facility and stores result in a view
-- Database: LEARNING_DB | Schema: HEALTH_DATA

CREATE OR REPLACE PROCEDURE LEARNING_DB.HEALTH_DATA.SP_PATIENT_COUNT_BY_FACILITY()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN
    CREATE OR REPLACE VIEW LEARNING_DB.HEALTH_DATA.VW_PATIENT_COUNT_BY_FACILITY AS
    SELECT
        f.FACILITY_ID,
        f.FACILITY_NAME,
        COUNT(DISTINCT a.PATIENT_ID) AS PATIENT_COUNT,
        CURRENT_TIMESTAMP() AS LAST_REFRESHED_AT
    FROM LEARNING_DB.HEALTH_DATA.FACILITIES f
    LEFT JOIN LEARNING_DB.HEALTH_DATA.ADMISSIONS a
        ON f.FACILITY_ID = a.FACILITY_ID
    GROUP BY f.FACILITY_ID, f.FACILITY_NAME;

    RETURN 'View VW_PATIENT_COUNT_BY_FACILITY refreshed successfully at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
